### PR TITLE
Added failing test for <rb> tag without surrounding <ruby>

### PR DESCRIPTION
**Pull request by sagotch**
I have no idea of why this one raises an error, but I am pretty sure it should not.

No idea if the test is put in the right place either, feel free to rewrite it as you wish.

If you have an idea of where to look at to fix this, I can try, but I am completely lost right now.

### CODE REVIEW

**Comment by aantron** [comment]
The parser case for `<rb>` elements has a bug. It does not call its continuation `mode'` if a `<ruby>` element is not in scope:

https://github.com/aantron/markup.ml/blob/7e2adca8389543b8a7335a12c57bff38a797640a/src/html_parser.ml#L1972-L1981

It's basically a missing `else`, but I think the solution will be a bit more convoluted than that because of the spec and the use of CPS.

The result of not calling the continuation is that the asynchronous parser "hangs." The synchronous wrapper fails to see the parser terminate, and raises `Markup.Synchronous.Not_synchronous`.

I will add a fix tomorrow. The case for `<rt>` elements below this one also has the bug.

It also looks like the [spec](https://www.w3.org/TR/html52/syntax.html#the-in-body-insertion-mode) has changed so that `<rp>` should be processed like `<rt>` rather than like `<rb>` since I wrote the code, or else that had always been a bug in Markup.ml, too.

**Comment by aantron** [comment]
The linked commit makes the parser not hang, and behave according to the spec, as I understood it.

Note that `<rb>a<rt>b` is parsed as `<rb>a<rt>b</rt></rb>` rather than `<ruby><rb>a</rb><rt>b</rt></ruby>`. I don't know if the first parse makes any kind of sense, but it seems that the spec doesn't direct the parser to insert a `<ruby>` element if one is not present in the input at all, which then doesn't trigger generating implied end tags, which would close the `<rb>` tag before the `<rt>` start tag.

If you'd like to double check that, click [here](https://www.w3.org/TR/html52/syntax.html#the-in-body-insertion-mode) and use Ctrl/Mac+F to search for the text `"rb"`. The case of interest is labeled *A start tag whose tag name is one of: "rb", "rtc"*.

**Comment by aantron** [comment]
The rules for parsing fragments also don't seem to assume that the fragment's context is `<ruby>` if the fragment begins with `<rb>`:

- https://www.w3.org/TR/html52/syntax.html#parsing-html-fragments
- https://www.w3.org/TR/html52/syntax.html#reset-the-insertion-mode-appropriately

**Comment by sagotch** [comment]
Thank you!

**Pull request closed without merging**
